CREATE TABLE COORDINATE
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME           VARCHAR(255)     NOT NULL,
    REGISTRY       VARCHAR(255)     NOT NULL,
    REGISTRY_VALUE VARCHAR(255)     NOT NULL,
    OWNER          CHAR(36)         NOT NULL,
    X_COORD        DOUBLE PRECISION NOT NULL,
    Y_COORD        DOUBLE PRECISION NOT NULL,
    Z_COORD        DOUBLE PRECISION NOT NULL
) CHARACTER SET utf8mb4;

CREATE UNIQUE INDEX UNIQUE_COORDS ON COORDINATE (NAME, OWNER)