version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "verysecurerootpassword"
      MARIADB_DATABASE: "coordreminder"
      MARIADB_USER: "coorduser"
      MARIADB_PASSWORD: "coordpassword"