CREATE TABLE COORDINATE
(
    ID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME           VARCHAR          NOT NULL,
    REGISTRY       VARCHAR          NOT NULL,
    REGISTRY_VALUE VARCHAR          NOT NULL,
    OWNER          UUID             NOT NULL,
    X_COORD        DOUBLE PRECISION NOT NULL,
    Y_COORD        DOUBLE PRECISION NOT NULL,
    Z_COORD        DOUBLE PRECISION NOT NULL
);

CREATE UNIQUE INDEX UNIQUE_COORDS ON COORDINATE (NAME, OWNER)